final List<String> presetNames = [
  'Wedding Glow Preset',
  'Moody Contrast Preset',
  'Light Green Harmony Preset',
  'Tokyo Nights Preset',
  'Bright & Airy Preset',
  'Vintage Film Preset',
  'Golden Hour Preset',
  'Urban Grit Preset',
  'Pastel Dream Preset',
  'Desert Warmth Preset',
  'Cinematic Shadows Preset',
  'Sunset Bliss Preset',
  'Matte Black Preset',
  'Autumn Hues Preset',
  'Soft Skin Tone Preset',
  'Tropical Vibes Preset',
  'Rustic Charm Preset',
  'Street Life Preset',
  'Dark Forest Preset',
  'Bright Portrait Preset',
  'Soft Pastel Preset',
  'Neon City Preset',
  'Deep Blue Ocean Preset',
  'Muted Tones Preset',
  'Monochrome Magic Preset',
  'Retro Vibes Preset',
  'Crisp Winter Preset',
  'Rose Gold Preset',
  'Dreamy Landscape Preset',
  'Soft Glow Preset',
];
