// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChqcT75QQ6QS2QoxUJGagjBbbcTVhikAg',
    appId: '1:465956513894:web:dd2ac9178f538e854e25a7',
    messagingSenderId: '465956513894',
    projectId: 'selling-app-b0ecc',
    authDomain: 'selling-app-b0ecc.firebaseapp.com',
    storageBucket: 'selling-app-b0ecc.appspot.com',
    measurementId: 'G-FJFF82LRJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOUPOpCyJmS987d9Itcf90HAam4KcMMw',
    appId: '1:465956513894:android:9d193bf57d2daee34e25a7',
    messagingSenderId: '465956513894',
    projectId: 'selling-app-b0ecc',
    storageBucket: 'selling-app-b0ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN3XwO5pLotzz-CsbzorDwqfjy9xuRMAY',
    appId: '1:465956513894:ios:3cb2b51201a7d6284e25a7',
    messagingSenderId: '465956513894',
    projectId: 'selling-app-b0ecc',
    storageBucket: 'selling-app-b0ecc.appspot.com',
    iosClientId: '465956513894-5mnshvpb7t2fdmqlmntdfs9nf5i7lloj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3XwO5pLotzz-CsbzorDwqfjy9xuRMAY',
    appId: '1:465956513894:ios:8ae295eaeb6f60d34e25a7',
    messagingSenderId: '465956513894',
    projectId: 'selling-app-b0ecc',
    storageBucket: 'selling-app-b0ecc.appspot.com',
    iosClientId: '465956513894-jdi6posk98arpnoi9fhro0qclat4igjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sellerApp.RunnerTests',
  );
}
